### ISSUE TITLE
Може варто перейменувати гру?

### ISSUE THREAD

**Issue by alexvoz** [hraimo/balda#2]
Бовдур, Ступа

Для релевантного пошуку "Балда" можна залишити в налаштуваннях пошуку та додати "... аналог гри Балда" в og тегах тощо

**Comment by vladhuk** [comment]
Привіт. Гарне зауваження, адже теж вважаю, що назва зросійщена, проте не впевнений, що наразі буде доцільно перейменовувати, адже абсолютна більшість людей шукає гру за запитом Балда і зміна назви може повести втрати і без того ще доволі малої аудиторії. Крім того в англомовних джерелах ця гра теж зветься саме Балда і її ніяк не перейменовують.
